### ISSUE TITLE
installer needs improvement

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/docgenerator#3]
- installer needs to install caddy with right plugins, maybe installing from source?
- maybe use our cuisine classes, they deal with caddy too?
- we need most used plugins, I think the std installed caddy doesn't have them, or maybe it does?
- basically we need to check the default caddy, that it supports the plugins, so people don't have to download it manually

**Comment by alichaddad** [comment]
fixed in https://github.com/Jumpscale/jumpscale_core8/commit/52906caa9c42970f1838359d5e016ae76c74882a and https://github.com/Jumpscale/jumpscale_core8/commit/4feda6d998f205ad9595904ae82315066d6f0d0b

**Comment by despiegk** [comment]
does this work on osx & linux now?
please add many other features there, use them all

**Comment by alichaddad** [comment]
Until  we have a better understanding of the required features, it is possible to specify the features in the cuisine installation: https://github.com/Jumpscale/jumpscale_core8/blob/8a167e5d52ccf2af1bb60daa08f398a976607f29/lib/JumpScale/tools/cuisine/apps/CuisineCaddy.py#L23
