### ISSUE TITLE
can get images to work properly

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/docgenerator#5]
see
http://themes.gohugo.io/beg/

for example see
/opt/code/github/jumpscale/docgenerator/examples/example1/def_test/blog/Images.md

**Comment by despiegk** [comment]
ehab can prob also help, because is going to be some html  kind of trick probably

**Comment by alichaddad** [comment]
The problem is that images need to be placed under `templates/blog/static/img` in order to work properly

**Comment by ehab-hassan** [comment]
done

**Comment by alichaddad** [comment]
see https://github.com/Jumpscale/docgenerator/commit/4ba227d28fa9a622d0d1d2b088868431301c15d0
