### ISSUE TITLE
mermaid default used css seems to be wrong

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/docgenerator#7]
![image](https://cloud.githubusercontent.com/assets/6021844/24391380/d40ca7e0-139f-11e7-9d81-8888b3b9c2e6.png)

- the fonts are too large
- probably need to put a css on the macro dir & use it in the mermaid cmd options

**Comment by alichaddad** [comment]
Added custom CSS file in https://github.com/Jumpscale/docgenerator/commit/02322cb26b4f6462ff709ce4b785ec0f3a0320ae
